[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = [
  "-Lnative=/home/developer/.xwin/crt/lib/x86_64",
  "-Lnative=/home/developer/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/developer/.xwin/sdk/lib/ucrt/x86_64"
]
